#!/bin/bash

deepspeed --num_gpus 1 ../../src/train_bash.py \
    --deepspeed ../deepspeed/ds_z3_config.json \
    --stage pt \
    --do_train \
    --model_name_or_path /home/v-leiwang8/llm_models/mistral-7B-v0.2 \
    --dataset example \
    --dataset_dir ../../data \
    --template mistral \
    --finetuning_type lora \
    --output_dir ../../saves/Mistral-7B-v0.2/full/pt_2 \
    --overwrite_cache \
    --overwrite_output_dir \
    --cutoff_len 1024 \
    --preprocessing_num_workers 16 \
    --per_device_train_batch_size 2 \
    --per_device_eval_batch_size 2 \
    --gradient_accumulation_steps 2 \
    --lr_scheduler_type cosine \
    --logging_steps 10 \
    --warmup_steps 20 \
    --save_steps 100 \
    --eval_steps 100 \
    --evaluation_strategy steps \
    --learning_rate 5e-5 \
    --num_train_epochs 3.0 \
    --max_samples 3000 \
    --val_size 0.1 \
    --ddp_timeout 180000000 \
    --plot_loss \
    --fp16
