### model
model_name_or_path: THUDM/glm-4-9b-chat
### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: query_key_value

### dataset
dataset: reward
template: glm4
cutoff_len: 8192
max_samples: 3000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/glm4/lora/sft_new
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

report_to: wandb
run_name: glm4_new